// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwGMPFeuvTHTCIbtDm67XDpyUIqrxmeZE',
    appId: '1:450664504269:web:0447ee4c3b56b48b488284',
    messagingSenderId: '450664504269',
    projectId: 'scenario-flutter-projet',
    authDomain: 'scenario-flutter-projet.firebaseapp.com',
    storageBucket: 'scenario-flutter-projet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCcKm5U-XtA2050nI74N9PLhUydr9NFg',
    appId: '1:450664504269:android:4bc945f8b6a10877488284',
    messagingSenderId: '450664504269',
    projectId: 'scenario-flutter-projet',
    storageBucket: 'scenario-flutter-projet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvERptsruyfLq_phAOWlbd7XG3X42uTN4',
    appId: '1:450664504269:ios:c6c24fad87760c23488284',
    messagingSenderId: '450664504269',
    projectId: 'scenario-flutter-projet',
    storageBucket: 'scenario-flutter-projet.firebasestorage.app',
    androidClientId: '450664504269-5ha2kjk8m1slc885r70ogflbn1umv0tm.apps.googleusercontent.com',
    iosClientId: '450664504269-nr8d8vcf3k2crub18qmr3hl3mkojt6hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.koko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvERptsruyfLq_phAOWlbd7XG3X42uTN4',
    appId: '1:450664504269:ios:c6c24fad87760c23488284',
    messagingSenderId: '450664504269',
    projectId: 'scenario-flutter-projet',
    storageBucket: 'scenario-flutter-projet.firebasestorage.app',
    androidClientId: '450664504269-5ha2kjk8m1slc885r70ogflbn1umv0tm.apps.googleusercontent.com',
    iosClientId: '450664504269-nr8d8vcf3k2crub18qmr3hl3mkojt6hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.koko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwGMPFeuvTHTCIbtDm67XDpyUIqrxmeZE',
    appId: '1:450664504269:web:cf7cfc00e4c39516488284',
    messagingSenderId: '450664504269',
    projectId: 'scenario-flutter-projet',
    authDomain: 'scenario-flutter-projet.firebaseapp.com',
    storageBucket: 'scenario-flutter-projet.firebasestorage.app',
  );
}
